### ISSUE TITLE
Servicenow cmdb hosts filtering 

### ISSUE THREAD

**Issue by hd2212** [vCarbs/Ansible#1]
Hey, I am facing problem with the host filtering process on Tower, while I'm able to pull hosts from the cmdb the limit restriction on my tower won't allow all the hosts to be populated into the inventory. So is there a way I could filter hosts with any tags on Tower? and for that do I have to add any lines in the .ini file?

**Comment by hd2212** [comment]
FYI: the .ini and .py file can be found in the below link url.

https://github.com/ServiceNowITOM/ansible-sn-inventory.git

**Comment by vCarbs** [comment]
Sorry, this is only for filtering VM's within vCenter.
